# 1.	Write a NumPy program to get the numpy version and show numpy build configuration.

In [3]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mangesh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mangesh/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mangesh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

# 2.	Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [35]:
arr = np.array([1+0j, 2+4j, 45, 8+8j, 79, 10j])
print(arr)

print(np.iscomplex(arr))
print(np.isreal(arr))
print(np.isscalar(6j))
print(np.isscalar([16]))
print(np.isscalar([70,40]))
print(np.isscalar(80))

[ 1. +0.j  2. +4.j 45. +0.j  8. +8.j 79. +0.j  0.+10.j]
[False  True False  True False  True]
[ True False  True False  True False]
True
False
False
True


# 3.	Write a NumPy program to test whether none of the elements of a given array is zero.

In [40]:
arr = np.array([10,20,30,40,50,1+6j])
print(arr)
print(np.all(arr))

arr = np.array([10,0,30,40,50,1+6j])
print(arr)
print(np.all(arr))


[10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j  1.+6.j]
True
[10.+0.j  0.+0.j 30.+0.j 40.+0.j 50.+0.j  1.+6.j]
False


# 4.	Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [41]:
my_list = [2,0,0,0,5,0,0,0]
arr =  np.array(my_list)
print(arr)
print(np.any(arr))

[2 0 0 0 5 0 0 0]
True


In [42]:
my_list = [0,0,0,0,0]
arr = np.array(my_list)
print(arr)
print(np.any(arr))

[0 0 0 0 0]
False


# 5.	Write a NumPy program to test element-wise for NaN of a given array.

In [43]:
my_list = [2,0,0,0,5,0,0,0]
arr =  np.array(my_list)
print(arr)
print(np.isnan(arr))

[2 0 0 0 5 0 0 0]
[False False False False False False False False]


In [46]:
my_list = [2,3,4,np.nan,46,7,np.nan]
arr = np.array(my_list)
print(arr)
print(np.isnan(arr))

[ 2.  3.  4. nan 46.  7. nan]
[False False False  True False False  True]


# 6.	Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [53]:
List = [2,3,5,7]
List1= [2,2,8,9]
arr = np.array(List)
arr1 = np.array(List1)
print("arr:",arr)
print("arr1:",arr1)
print("Elementwise comparision")
print("----GREATER THAN----")
print(np.greater(arr,arr1))
print("----GREATER EQUAL TO----")
print(np.greater_equal(arr,arr1))
print("----LESS----")
print(np.less(arr,arr1))
print("----LESS EQUAL----")
print(np.less_equal(arr,arr1))

arr: [2 3 5 7]
arr1: [2 2 8 9]
Elementwise comparision
----GREATER THAN----
[False  True False False]
----GREATER EQUAL TO----
[ True  True False False]
----LESS----
[False False  True  True]
----LESS EQUAL----
[ True False  True  True]


# 7.	Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
## Input:
## x = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
## y = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])


In [57]:
x = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x,y))
print(np.allclose(x,y))


[ True  True  True  True  True  True  True  True  True False]
True


# 8.	Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [59]:
my_list = [1,5,5,6,7,8,9,10,15,100]
arr = np.array(my_list)
print(arr)
print("Size of array :",arr.size)
print("Memory occupied each element in array:",arr.itemsize)
print("Memory occupied by whole array:",arr.size * arr.itemsize)

[  1   5   5   6   7   8   9  10  15 100]
Size of array : 10
Memory occupied each element in array: 4
Memory occupied by whole array: 40


# 9.	Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [62]:
arr = np.zeros(10,dtype=int)
print(arr)
print("Size:",arr.size)
arr = np.ones(10,dtype =int)
print(arr)
print("Size:",arr.size)
arr = np.ones(10, dtype =int) *5
print(arr)
print("Size:",arr.size)

[0 0 0 0 0 0 0 0 0 0]
Size: 10
[1 1 1 1 1 1 1 1 1 1]
Size: 10
[5 5 5 5 5 5 5 5 5 5]
Size: 10


# 10.	Write a NumPy program to create an array of the integers from 30 to 70.

In [65]:
arr = np.arange(start=30,stop=71,dtype=int)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# 11.	Write a NumPy program to create an array of all the even integers from 30 to 70.

In [75]:
arr= np.arange(start=30,stop=71,step=2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# 12.	Write a NumPy program to create a 3x3 identity matrix

In [71]:
matrix = np.identity(3 ,dtype=int)
print(matrix)


# OR 

matrix =np.eye(3, dtype=int)
print(matrix)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


# 13.	Write a NumPy program to generate a random number between 0 and 1.

In [90]:
arr =np.random.randint(low=0, high=1,size=10)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


# 14.	Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [72]:
arr_of_random_numbers = np.random.normal(5,2,15)
print(arr_of_random_numbers)

[4.2328095  4.22254603 4.86435918 7.41614763 7.33289848 4.04383187
 3.10080223 8.06035898 4.55374158 5.07396422 1.70862304 4.5156041
 3.77730834 4.80507561 7.86221467]




# 15.	Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [91]:
vector = np.arange(15,56)
print(vector)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [94]:
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
