In [3]:
import numpy as np

In [5]:
rows = int(input("Enter row size:"))
columns = int(input("Enter column size:"))


matrix = np.ndarray(shape=(rows,columns),dtype=int)
print(matrix)

Enter row size:4
Enter column size:3
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
print("Size of the matrix:",matrix.size)
print("Shape of matrix:",matrix.shape)
print("Dimesions of matrix:",matrix.ndim)
print("Datatype of the matrix:",matrix.dtype)


Size of the matrix: 12
Shape of matrix: (4, 3)
Dimesions of matrix: 2
Datatype of the matrix: int32


In [8]:
for row in matrix:
    for ele in row:
        print(ele, end=" ")
    print()

0 0 0 
0 0 0 
0 0 0 
0 0 0 


In [9]:
arr = np.ndarray(shape=(5),dtype=int)
print(arr)

n= arr.size
for i in range(n):
    arr[i]=int(input("Enter elements for array:"))
print(arr)

[4128860 6029375 3801155 3014748 6750312]
Enter elements for array:14
Enter elements for array:15
Enter elements for array:16
Enter elements for array:17
Enter elements for array:18
[14 15 16 17 18]


In [11]:
print("Size:",arr.size)
print("Shape:",arr.shape)
print("dimensions:",arr.ndim)
print("Datatype:",arr.dtype)

Size: 5
Shape: (5,)
dimensions: 1
Datatype: int32


In [17]:
r= int(input("Enter number of rows you want:"))
c= int(input("enter number of columns you want:"))
mat = np.ndarray (shape=(r,c), dtype=int)
print(mat)
for i in range(r):

    for j in range (c):
        mat[i][j]= int(input())
print(mat)

Enter number of rows you want:4
enter number of columns you want:3
[[44  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]
44
55
66
77
88
99
100
42
56
21
20
10
[[ 44  55  66]
 [ 77  88  99]
 [100  42  56]
 [ 21  20  10]]
