In [1]:
import numpy as np

In [2]:
n=int(input("Enter the size"))
arr = np.ndarray(shape=(n),dtype=int)
print(arr)

Enter the size5
[-702277504        446          0          0     131074]


In [4]:
n=int(input("Enter the size:"))
a = np.ndarray(shape=(n),dtype=int)
print(a)
print("Enter %d elements:"%n)
for i in range(n):
    a[i]= int(input())
print(a)

Enter the size:5
[-701878256        446          0          0          1]
Enter 5 elements:
5
4
6
2
1
[5 4 6 2 1]


In [5]:
n=int(input("Enter the size:"))
array = np.ndarray(shape=(n))
print(array)
print("enter %d elements:"%n)
for i in range(n):
    array[i]=input()
print(array)

Enter the size:6
[0. 0. 0. 0. 0. 0.]
enter 6 elements:
4
5
8
10
45
60
[ 4.  5.  8. 10. 45. 60.]


In [6]:
n=int(input("Enter the size:"))
ar = np.ndarray(shape=(n))
print(ar)
print("enter %d elements:"%n)
for i in range(n):
    ar[i]=int(input())
print(ar)

Enter the size:4
[9.48203159e-312 1.29060531e-306 1.02359984e-306 2.22522596e-306]
enter 4 elements:
5
6
7
8
[5. 6. 7. 8.]
