In [1]:
import numpy as np


In [3]:
m=int(input("Enter the value:"))
r=int(input("rows you want:"))
c=int(input("columns you want:"))
matrix = np.ndarray(shape=(m,r,c),dtype=int)
print(matrix)

Enter the value:2
rows you want:3
columns you want:3
[[[      0       0       0]
  [      0       0       0]
  [      0       0       0]]

 [[      0    1636       0]
  [      0 6553710       0]
  [4456540 4980812     115]]]


In [5]:
for i in range(m):
    for j in range(r):
        for k in range(c):
            matrix[i][j][k]=int(input())
print(matrix)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
18
[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 18]]]


In [6]:
print(matrix)

[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 18]]]
