# ndmin - specifies minimum dimensions of array

In [5]:
import numpy as np
a = np.array([10,20,30,40],ndmin=2)
print(a)
print("Dimensions:",a.ndim)
print("Shape:",a.shape)

[[10 20 30 40]]
Dimensions: 2
Shape: (1, 4)


In [7]:
a = np.array([10,20,30,40],ndmin=1)
print(a)
print("Dimensions:",a.ndim)
print("Shape:",a.shape)

[10 20 30 40]
Dimensions: 1
Shape: (4,)


In [21]:
a = np.array([10,20,30,40,50],dtype=complex)
print(a)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j]


In [22]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [24]:
a.shape = (3,2)

In [25]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [28]:

a = np.array([[1,2,3],[4,5,6]])
print(a)
b=a.reshape(3,2)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [29]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [30]:
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [42]:
for i in range(2):
    for j in range(4):
        for k in range(3):
            print(b[i][j][k],end=' ')
        print()

0 1 2 
3 4 5 
6 7 8 
9 10 11 
12 13 14 
15 16 17 
18 19 20 
21 22 23 


In [43]:
for i in range(2):
    for j in range(4):
        print(b[i][j])

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


In [44]:
for i in range(2):
    print(b[i])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [45]:
print(b.itemsize)
# This array attribute returns the length of each element of array in bytes.

4


In [47]:
x= np.array([1,2,3,4],dtype=np.int8)
print(x.itemsize)

1


In [48]:
x= np.array([1,2,3,4],dtype=np.int32)
print(x.itemsize)

4


In [53]:
x= np.array([1,2,3,4],dtype=np.float32)
print(x.itemsize)

4


In [54]:
x= np.array([1,2,3,4],dtype = np.float64)
print(x.itemsize)

8


In [61]:
z = np.empty(10,dtype = int)
print(z)

[         0 1076101120          0 1077149696          0 1077805056
          0 1078198272          0 1078525952]


In [62]:
w = np.empty([3,4],dtype=int)
print(w)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [64]:
k = np.empty([4,4], dtype=int)
print(k)

[[      0       0       0       0]
 [      0       0       0       0]
 [      0       0    1980       0]
 [      0 7340078       0 6881280]]


In [67]:
l = np.empty(shape=(5,4),dtype=int)
print(l) 

[[         0 1076101120          0          0]
 [         0 1077149696          0          0]
 [         0 1077805056          0          0]
 [         0 1078198272          0          0]
 [         0 1078525952          0          0]]


In [68]:
z = np.zeros ([2,3], dtype=int)

In [69]:
print(z)

[[0 0 0]
 [0 0 0]]


In [70]:
z=np.zeros([4,4],dtype=int)

In [71]:
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [72]:
  = np.zeros(shape=(10,4), dtype=int)0
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [73]:
z = np.zeros(10)

In [74]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [75]:
print(z.itemsize)

8


In [76]:
z= np.zeros(10, dtype=int)
print(z)

[0 0 0 0 0 0 0 0 0 0]


In [77]:
z = np.ones(shape=(4,3),dtype=int)
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [78]:
z = np.ones([5,6], dtype= int)
print(z)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [79]:
z= np.ones(5)
print(z)

[1. 1. 1. 1. 1.]


In [81]:
my_list= [1,2,3,4,5,6]
a = np.asarray(my_list,dtype= float)

print(a)
#This function is similar to numpy.array 
#except for the fact that it has fewer parameters

[1. 2. 3. 4. 5. 6.]


In [82]:
Tuple = (10,20,30,40,50,60)
res = np.asarray(Tuple)
print(res)

[10 20 30 40 50 60]


In [84]:
x = [(10,20,30,40,50),(100,200)]
a= np.asarray(x)
print(a)

[(10, 20, 30, 40, 50) (100, 200)]


In [87]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)
print("Dimensions:",a.ndim)

[(1, 2, 3) (4, 5)]
Dimensions: 1


In [91]:
print(a [0]);print(a[1])

(1, 2, 3)
(4, 5)


In [92]:
print("Size:", a.size)

Size: 2


# nump.arange
# This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −
## numpy.arange(start, stop, step, dtype)

## start 
### The start of an interval. If omitted, defaults to 0.


## stop 
### The end of an interval (not including this number)


## step 
### Spacing between values, default is 1

## dtype 
### Data type of resulting ndarray. If not given, data type of input is used


In [95]:
x = np.arange(10.0)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [97]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [101]:
x = np.arange(0,21,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [102]:
x = np.arange(10,dtype=float)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [103]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


## • numpy.linspace 
## • This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows − 
### • numpy.linspace(start, stop, num, endpoint, retstep, dtype


## 1 start 
### The starting value of the sequence 
## 2 stop 
### The end value of the sequence, included in the sequence if endpoint set to true 
## 3 num 
### The number of evenly spaced samples to be generated. Default is 50 
## 4 endpoint 
### True by default, hence the stop value is included in the sequence. If false, it is not included 
## 5 retstep 
### If true, returns samples and step between the consecutive numbers 
## 6 dtype 
### Data type of output ndarray


In [104]:
x =np.linspace(1,10) 
print(x)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [109]:
x= np.linspace(start=1, stop=10, num=20,endpoint = False,retstep = True)
print(x)

(array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55]), 0.45)


In [110]:
x= np.linspace(start=1,stop=5,endpoint=True,retstep=True)
print(x)

(array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]), 0.08163265306122448)


In [113]:
x = np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [114]:
x= np.linspace(start=20,stop=21,num=10,endpoint=True,retstep=True)
print(x)

(array([20.        , 20.11111111, 20.22222222, 20.33333333, 20.44444444,
       20.55555556, 20.66666667, 20.77777778, 20.88888889, 21.        ]), 0.1111111111111111)


## numpy.logspace
<font color='Blue'> 
### • This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.
### • numpy.logspace(start, stop, num, endpoint, base, dtype)</font>


In [115]:
#<font color='green'>text</font> To color the text

In [134]:
a = np.logspace(1,3,num=3,base=10)
print(a) # 10^1   10^2  10^3

[  10.  100. 1000.]


In [135]:
a = np.logspace(1,4,num=10,base=10)
print(a)

[   10.            21.5443469     46.41588834   100.
   215.443469     464.15888336  1000.          2154.43469003
  4641.58883361 10000.        ]


In [137]:
a = np.logspace(1,3,num=5,endpoint= True,base=2)
print(a)

[2.         2.82842712 4.         5.65685425 8.        ]


# Indexing and Slicing
### • A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array

In [140]:
a =np.arange(10)
print(a)
s=slice(2,7,2)
print(a[s])


[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [141]:
 a= np.arange(10)

In [142]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [143]:
print(a[:5])

[0 1 2 3 4]


In [144]:
print(a[2:7:2])

[2 4 6]


# NumPy - Iterating Over Array 
## • numpy.nditer. 
### It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface

In [148]:
a = np.arange(0,60,5)
print(a)
a= a.reshape(3,4)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [153]:
for x in np.nditer(a):
    print(x,end=" ")


0 5 10 15 20 25 30 35 40 45 50 55 

In [151]:
 a= np.arange(0,60,5)

In [154]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print( 'Sorted in C-style order:') 
for x in np.nditer(a, order = 'C'): # row major
    print (x)
print( '\n') 
print ('Sorted in F-style order:') 
for x in np.nditer(a, order = 'F'): # column major
    print (x)

Sorted in C-style order:
0
5
10
15
20
25
30
35
40
45
50
55


Sorted in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


# Filter


In [166]:
import pandas as pd

area = [423967, 695662, 141297, 170312, 149995] 
population = [38332521, 26448193, 19651127, 19552860, 12882135] 
index = ['California', 'Texas', 'New York', 'Florida', 'Illinois'] 
df = pd.DataFrame({'area': area, 'population': population}, index=index) 
df['density'] = df.population / df.area 
print(density) 
dense_states = density > 100 
print(dense_states) 
large_states = df.area > 500000 
print(large_states)

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
dtype: float64
California    False
Texas         False
New York       True
Florida        True
Illinois      False
dtype: bool
California    False
Texas          True
New York      False
Florida       False
Illinois      False
Name: area, dtype: bool


In [163]:
df

area  population     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763