In [1]:
import numpy as np

In [6]:
my_list = [10,20,30,40,50,60]
arr = np.array(my_list)
print("Array:",arr)
print("size:",arr.size)
print("Shape:",arr.shape)
print("Dimensions:",arr.dtype)
print("Dimensions:",arr.ndim)

Array: [10 20 30 40 50 60]
size: 6
Shape: (6,)
Dimensions: int32
Dimensions: 1


In [7]:
res = arr.reshape(2,3)
print(res)
print("Dimensions:",res.ndim)

[[10 20 30]
 [40 50 60]]
Dimensions: 2


In [9]:
res = arr.reshape(3,2)
print(res)
print("Dimensions:",res.ndim)

[[10 20]
 [30 40]
 [50 60]]
Dimensions: 2


In [10]:
my_list = [10,20,30,40,50,60,70,80]
matrix = np.array(my_list)
print("Matrix:",matrix)
print("size:",matrix.size)
print("Shape:",matrix.shape)
print("Dimensions:",matrix.dtype)
print("Dimensions:",matrix.ndim)

Matrix: [10 20 30 40 50 60 70 80]
size: 8
Shape: (8,)
Dimensions: int32
Dimensions: 1


In [12]:
res = matrix.reshape(2,2,2)
print(res)
print("Dimesions:",res.ndim)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
Dimesions: 3
