In [1]:
import numpy as np

In [2]:
my_list=[10,20,30,40,50]
arr= np.array(my_list)

In [4]:
print(arr),type(arr)

[10 20 30 40 50]


(None, numpy.ndarray)

# Find the Proporties of Array

In [11]:
print("Array:",arr)
print("Size:",arr.size)
print("Datatype:",arr.dtype)
print("Dimension:",arr.ndim)
print("Shape:",arr.shape)

Array: [10 20 30 40 50]
Size: 5
Datatype: int32
Dimension: 1
Shape: (5,)


In [12]:
my_list = [[10,20,30],[40,50,60],[70,80,90]]
matrix = np.array(my_list)
print("Matrix:",matrix)
print("Size:",matrix.size)
print("Datatype:",matrix.dtype)
print("Dimension:",matrix.ndim)
print("Shape:",matrix.shape)

Matrix: [[10 20 30]
 [40 50 60]
 [70 80 90]]
Size: 9
Datatype: int32
Dimension: 2
Shape: (3, 3)


# Arry from List

In [14]:
my_list= [10,20,30,40,50]
arr = np.array(my_list)
print("Elements:")
for elements in arr:
    print(elements)

Elements:
10
20
30
40
50


In [17]:
# Two dimensional array

my_list=[[10,20,30],[40,50,60],[70,80,90]]
matrix = np.array(my_list)
print("Elements:")
print(matrix)




Elements:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
for row in matrix:
    print(row)

[10 20 30]
[40 50 60]
[70 80 90]


In [21]:
for row in matrix:
    for ele in row:
        print(ele,end= " ")
    print()

10 20 30 
40 50 60 
70 80 90 


# Sub matrix from Matrix using Slicing

In [22]:
my_list = [[10,20,30],[40,50,60],[70,80,90]]
matrix = np.array(my_list)
print(matrix)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [24]:
# [ row_lwr_bound : rwo_upper_bound , col_low : col_upp]
res = matrix[:,:]
print(res)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [37]:
res = matrix [0:3, 0:3]

In [38]:
print(res)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [41]:
res = matrix[1:3,1:3]

In [42]:
print(res)

[[50 60]
 [80 90]]


In [43]:
print(matrix[0:2,0:3])

[[10 20 30]
 [40 50 60]]


In [44]:
print(matrix[0:3,0:2]) #three row and two columns

[[10 20]
 [40 50]
 [70 80]]


# Creating One dimensional Array using ndarray function

In [47]:
n= int(input("Enter sizeddd:"))
array = np.ndarray(shape = (n), dtype=int)
print(array)


Enter size:5
[-899507600        579          0          0          1]
