# 1.	  Write a NumPy program to create a 3X4 array using and iterate over it.

In [9]:
import numpy as np
matrix = np.arange(1,13)
print(matrix)
res = matrix.reshape(3,4)
print(res)

for i in np.nditer(res):
    print(i,end=" ")
print()
    
# OR

for i in range(0,3):
    for j in range(0,4):
        print(res[i][j],end=" ")
    print()
    

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 
1 2 3 4 
5 6 7 8 
9 10 11 12 


# 2.	Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [22]:
import numpy as np
arr = np.linspace(10,49,5,endpoint=True,retstep=True)
print(arr)


(array([10.  , 19.75, 29.5 , 39.25, 49.  ]), 9.75)


# 3.	Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [31]:
arr = np.arange(21)
print(arr)


arr[(arr>=9)  &  (arr <= 15)] *= -1
print(arr)

# OR 

#for i in range(9,16):
    #arr[i]*=-1
#print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


# 4.	 Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [33]:
arr = np.random.randint(low=0,high=11,size=5)
print(arr)

[7 1 3 0 8]


# 5.	Write a NumPy program to multiply the values of two given vectors.

In [34]:
arr1 = np.random.randint(low =1 , high = 15,size=4)
arr2 = np.random.randint(low =1 , high = 15,size=4)
result = arr1 * arr2
print(arr1)
print(arr2)
print(result)

[4 4 5 1]
[14  4  6  4]
[56 16 30  4]


# 6.	Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [36]:
matrix = np.arange(start=10, stop=22).reshape(3,4)
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# 7. Write a NumPy program to find the number of rows and columns of a given matrix.

In [39]:
matrix = np.arange(start=10, stop=22).reshape(3,4)
print(matrix)
print("Rows and columns of matrix::",matrix.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Rows and columns of matrix:: (3, 4)


# 8.	Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [44]:
matrix = np.identity(3,dtype=int)
print(matrix)

# OR

mat = np.eye(3,dtype=int)
print(mat)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


# 9.	 Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [51]:
matrix = np.ones(shape = (10,10) , dtype = int)
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [56]:
matrix[1:-1,1:-1]=0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 10.	Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [59]:
my_list=[1,2,3,4,5]
matrix = np.diag(my_list)
print(matrix)



[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 11.	Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [64]:
matrix = np.zeros((4,4))
print(matrix)
matrix[::2,1::2] = 1
matrix[1::2,::2] = 1
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


# 12.	Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [68]:
matrix = np.random.random((3,3,3))
print(matrix)

[[[0.43036849 0.14868556 0.74345865]
  [0.36846508 0.07173919 0.52616045]
  [0.33076924 0.82549741 0.28148717]]

 [[0.18813351 0.51319368 0.34202168]
  [0.68683737 0.60458976 0.71581934]
  [0.20322134 0.50918824 0.89460958]]

 [[0.6084088  0.17971772 0.92797143]
  [0.341017   0.5933595  0.31987204]
  [0.37319188 0.06330081 0.57806549]]]


# 13.	Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array. 

In [70]:
my_list = [[4,5],[8,9]]
arr = np.array(my_list)
print(arr)
print("Sum of all elements:",np.sum(arr))
print("Sum of each column:",np.sum(arr,axis=0))
print("Sum of each row:",np.sum(arr,axis=1))


[[4 5]
 [8 9]]
Sum of all elements: 26
Sum of each column: [12 14]
Sum of each row: [ 9 17]


# 14.	Write a NumPy program to compute the inner product of two given vectors.

In [71]:
arr1 = np.array([5,10])
arr2 = np.array([8,55])
print("arr1:",arr1)
print("arr2:",arr2)
print("-------Inner product------")
print(np.dot(arr1,arr2))

arr1: [ 5 10]
arr2: [ 8 55]
-------Inner product------
590


# 15.	Write a NumPy program to add a vector to each row of a given matrix

In [84]:
arr = np.arange(1,22).reshape(3,7)
print("matrix:")
print(arr)
vector = np.array([4,6,4,2,3,1,7])
print("Vector:",vector)


matrix:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
Vector: [4 6 4 2 3 1 7]


In [85]:
for i in range(0,3):
    for j in range(0,7):
        arr[i][j] =arr[i][j] + vector[j]
print(arr)

[[ 5  8  7  6  8  7 14]
 [12 15 14 13 15 14 21]
 [19 22 21 20 22 21 28]]
